[measurement_settings]
device = "Dev2"
sampling_rate_hz = 2
nidaq_buffer_len_sec = 10
software_polling_hz = 0.3

[[port]]
name = "Vent"
channel = "ai0"
sample_type = "DIFF"
min_val = -5
max_val = 5

[[port]]
name = "Load Cell"
channel = "ai1"
sample_type = "DIFF"
min_val = -0.02
max_val = 0.02